class MyClass:
    ''' class generated by Vishal Mahajan '''           #__doc__

print(MyClass.__doc__)          # access docstring of the class
print(MyClass.__dict__)         # access dictionary containing class attribute
help(MyClass)                   # get information about the class